apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-location
  namespace: temperaturaapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-location
  template:
    metadata:
      labels:
        app: api-location
    spec:
      containers:
      - name: api-location
        image: api-location:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5672"
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/temperaturadb"
        - name: REDIS_URL
          value: "redis:6379"
        - name: SQLITE_PATH
          value: "/data/transactions.db"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4318"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        volumeMounts:
        - name: sqlite-data
          mountPath: /data
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests: { memory: 128Mi, cpu: 100m }
          limits:   { memory: 256Mi, cpu: 500m }
      volumes:
      - name: sqlite-data
        persistentVolumeClaim:
          claimName: sqlite-data-pvc
